from datetime import datetime

from relational_fraud_intelligence.domain.models import (
    AccountProfile,
    CustomerProfile,
    DeviceProfile,
    FraudScenario,
    InvestigatorNote,
    MerchantProfile,
    ScenarioTag,
    TransactionChannel,
    TransactionRecord,
    TransactionStatus,
)


def build_demo_scenarios() -> tuple[FraudScenario, ...]:
    synthetic_identity_ring = FraudScenario(
        scenario_id="synthetic-identity-ring",
        title="Synthetic Identity Gift Card Ring",
        industry="Fintech",
        summary="Two recently opened accounts are liquidating digital gift cards from the same device cluster.",
        hypothesis="A synthetic identity ring is onboarding low-history users, sharing infrastructure, and cashing out through high-risk merchants.",
        tags=[ScenarioTag.FRAUD, ScenarioTag.SYNTHETIC_IDENTITY, ScenarioTag.DEVICE_RING, ScenarioTag.CROSS_BORDER],
        customers=[
            CustomerProfile(
                customer_id="cust_amina",
                full_name="Amina Rahman",
                country_code="US",
                segment="consumer-checking",
                declared_income_band="$40k-$60k",
                linked_account_ids=["acct_amina"],
                linked_device_ids=["dev_shared_1"],
                watchlist_tags=["thin-file"],
            ),
            CustomerProfile(
                customer_id="cust_noah",
                full_name="Noah Carter",
                country_code="US",
                segment="consumer-checking",
                declared_income_band="$30k-$50k",
                linked_account_ids=["acct_noah"],
                linked_device_ids=["dev_shared_1", "dev_burner_9"],
                watchlist_tags=["address-mismatch"],
            ),
        ],
        accounts=[
            AccountProfile(
                account_id="acct_amina",
                customer_id="cust_amina",
                opened_at=datetime.fromisoformat("2026-02-25T09:15:00"),
                current_balance=820.0,
                average_monthly_inflow=2100.0,
                chargeback_count=1,
                manual_review_count=2,
            ),
            AccountProfile(
                account_id="acct_noah",
                customer_id="cust_noah",
                opened_at=datetime.fromisoformat("2026-02-28T12:20:00"),
                current_balance=610.0,
                average_monthly_inflow=1800.0,
                chargeback_count=2,
                manual_review_count=3,
            ),
        ],
        devices=[
            DeviceProfile(
                device_id="dev_shared_1",
                fingerprint="fp-shared-lenovo-001",
                ip_country_code="US",
                linked_customer_ids=["cust_amina", "cust_noah"],
                trust_score=0.19,
            ),
            DeviceProfile(
                device_id="dev_burner_9",
                fingerprint="fp-burner-android-774",
                ip_country_code="NL",
                linked_customer_ids=["cust_noah"],
                trust_score=0.11,
            ),
        ],
        merchants=[
            MerchantProfile(
                merchant_id="merch_giftloop",
                display_name="GiftLoop Digital Vault",
                country_code="NL",
                category="digital_goods",
                description="Bulk digital gift card marketplace with instant resale routing.",
            ),
            MerchantProfile(
                merchant_id="merch_streamarc",
                display_name="StreamArc Media",
                country_code="US",
                category="subscription",
                description="Streaming bundle seller with frequent card testing indicators.",
            ),
        ],
        transactions=[
            TransactionRecord(
                transaction_id="txn_1001",
                customer_id="cust_amina",
                account_id="acct_amina",
                device_id="dev_shared_1",
                merchant_id="merch_giftloop",
                occurred_at=datetime.fromisoformat("2026-03-08T14:03:00"),
                amount=1250.0,
                currency="USD",
                channel=TransactionChannel.CARD_NOT_PRESENT,
                status=TransactionStatus.APPROVED,
            ),
            TransactionRecord(
                transaction_id="txn_1002",
                customer_id="cust_amina",
                account_id="acct_amina",
                device_id="dev_shared_1",
                merchant_id="merch_giftloop",
                occurred_at=datetime.fromisoformat("2026-03-08T14:07:00"),
                amount=1125.0,
                currency="USD",
                channel=TransactionChannel.CARD_NOT_PRESENT,
                status=TransactionStatus.REVIEW,
            ),
            TransactionRecord(
                transaction_id="txn_1003",
                customer_id="cust_noah",
                account_id="acct_noah",
                device_id="dev_shared_1",
                merchant_id="merch_giftloop",
                occurred_at=datetime.fromisoformat("2026-03-08T14:09:00"),
                amount=980.0,
                currency="USD",
                channel=TransactionChannel.WALLET,
                status=TransactionStatus.REVIEW,
            ),
            TransactionRecord(
                transaction_id="txn_1004",
                customer_id="cust_noah",
                account_id="acct_noah",
                device_id="dev_burner_9",
                merchant_id="merch_giftloop",
                occurred_at=datetime.fromisoformat("2026-03-08T14:16:00"),
                amount=1410.0,
                currency="USD",
                channel=TransactionChannel.CARD_NOT_PRESENT,
                status=TransactionStatus.APPROVED,
            ),
            TransactionRecord(
                transaction_id="txn_1005",
                customer_id="cust_noah",
                account_id="acct_noah",
                device_id="dev_burner_9",
                merchant_id="merch_streamarc",
                occurred_at=datetime.fromisoformat("2026-03-09T10:02:00"),
                amount=24.99,
                currency="USD",
                channel=TransactionChannel.CARD_NOT_PRESENT,
                status=TransactionStatus.APPROVED,
            ),
        ],
        investigator_notes=[
            InvestigatorNote(
                note_id="note_2001",
                subject_customer_id="cust_amina",
                author="risk.ops@bank.example",
                created_at=datetime.fromisoformat("2026-03-08T15:00:00"),
                body="Manual review found a shared device fingerprint across two new identities. Gift card liquidation pattern suggests synthetic identity behavior.",
            ),
            InvestigatorNote(
                note_id="note_2002",
                subject_customer_id="cust_noah",
                author="fraud.analyst@bank.example",
                created_at=datetime.fromisoformat("2026-03-09T09:30:00"),
                body="Second profile used a burner Android after verification failure. Behavior is consistent with mule-style cash out through digital goods.",
            ),
        ],
    )

    account_takeover = FraudScenario(
        scenario_id="travel-ato-escalation",
        title="Travel Account Takeover Escalation",
        industry="Digital Banking",
        summary="A long-tenured customer shifts to a new foreign device and starts a fast sequence of cross-border spend.",
        hypothesis="Credential stuffing or SIM swap led to account takeover and rapid spend from a new device.",
        tags=[ScenarioTag.FRAUD, ScenarioTag.ACCOUNT_TAKEOVER, ScenarioTag.CROSS_BORDER],
        customers=[
            CustomerProfile(
                customer_id="cust_olivia",
                full_name="Olivia Chen",
                country_code="US",
                segment="premium-checking",
                declared_income_band="$120k-$150k",
                linked_account_ids=["acct_olivia"],
                linked_device_ids=["dev_known_olivia", "dev_unknown_prague"],
                watchlist_tags=[],
            ),
        ],
        accounts=[
            AccountProfile(
                account_id="acct_olivia",
                customer_id="cust_olivia",
                opened_at=datetime.fromisoformat("2021-06-11T08:00:00"),
                current_balance=19450.0,
                average_monthly_inflow=11600.0,
                chargeback_count=0,
                manual_review_count=1,
            ),
        ],
        devices=[
            DeviceProfile(
                device_id="dev_known_olivia",
                fingerprint="fp-iphone-olivia-002",
                ip_country_code="US",
                linked_customer_ids=["cust_olivia"],
                trust_score=0.93,
            ),
            DeviceProfile(
                device_id="dev_unknown_prague",
                fingerprint="fp-emulator-prg-443",
                ip_country_code="CZ",
                linked_customer_ids=["cust_olivia"],
                trust_score=0.08,
            ),
        ],
        merchants=[
            MerchantProfile(
                merchant_id="merch_airlift",
                display_name="Airlift Tickets",
                country_code="CZ",
                category="travel",
                description="Instant delivery travel booking platform.",
            ),
            MerchantProfile(
                merchant_id="merch_wirez",
                display_name="Wirez Transfer Hub",
                country_code="LT",
                category="money_transfer",
                description="Cross-border payout processor often used for rapid disbursement.",
            ),
        ],
        transactions=[
            TransactionRecord(
                transaction_id="txn_2001",
                customer_id="cust_olivia",
                account_id="acct_olivia",
                device_id="dev_unknown_prague",
                merchant_id="merch_airlift",
                occurred_at=datetime.fromisoformat("2026-03-10T18:14:00"),
                amount=1980.0,
                currency="USD",
                channel=TransactionChannel.CARD_NOT_PRESENT,
                status=TransactionStatus.APPROVED,
            ),
            TransactionRecord(
                transaction_id="txn_2002",
                customer_id="cust_olivia",
                account_id="acct_olivia",
                device_id="dev_unknown_prague",
                merchant_id="merch_wirez",
                occurred_at=datetime.fromisoformat("2026-03-10T18:19:00"),
                amount=2400.0,
                currency="USD",
                channel=TransactionChannel.BANK_TRANSFER,
                status=TransactionStatus.REVIEW,
            ),
            TransactionRecord(
                transaction_id="txn_2003",
                customer_id="cust_olivia",
                account_id="acct_olivia",
                device_id="dev_unknown_prague",
                merchant_id="merch_wirez",
                occurred_at=datetime.fromisoformat("2026-03-10T18:22:00"),
                amount=2600.0,
                currency="USD",
                channel=TransactionChannel.BANK_TRANSFER,
                status=TransactionStatus.REVIEW,
            ),
        ],
        investigator_notes=[
            InvestigatorNote(
                note_id="note_3001",
                subject_customer_id="cust_olivia",
                author="security@bank.example",
                created_at=datetime.fromisoformat("2026-03-10T18:40:00"),
                body="Customer reported a possible SIM swap and could not access MFA. New emulator device initiated cross-border travel and transfer spend within minutes.",
            ),
        ],
    )

    return synthetic_identity_ring, account_takeover
