from typing import Protocol

from relational_fraud_intelligence.application.dto.investigation import (
    GetScenarioQuery,
    GetScenarioResult,
    ListScenariosQuery,
    ListScenariosResult,
)
from relational_fraud_intelligence.domain.models import (
    AlertStatus,
    AnalysisResult,
    CaseComment,
    CasePriority,
    CaseStatus,
    Dataset,
    FraudAlert,
    FraudCase,
    RiskLevel,
    UploadedTransaction,
    WorkflowSourceType,
)


class ScenarioRepository(Protocol):
    def list_scenarios(self, query: ListScenariosQuery) -> ListScenariosResult: ...

    def get_scenario(self, query: GetScenarioQuery) -> GetScenarioResult: ...


class CaseRepository(Protocol):
    """Port for persistent fraud case storage."""

    def create_case(self, case: FraudCase) -> None: ...
    def get_case(self, case_id: str) -> FraudCase | None: ...
    def update_case(self, case: FraudCase) -> None: ...
    def list_cases(
        self,
        *,
        status: CaseStatus | None = None,
        priority: CasePriority | None = None,
        assigned_analyst_id: str | None = None,
        page: int = 1,
        page_size: int = 20,
    ) -> tuple[list[FraudCase], int]: ...
    def add_comment(self, comment: CaseComment) -> None: ...
    def list_comments(self, case_id: str) -> list[CaseComment]: ...
    def count_by_status(self) -> dict[str, int]: ...
    def count_critical(self) -> int: ...


class AlertRepository(Protocol):
    """Port for persistent fraud alert storage."""

    def create_alert(self, alert: FraudAlert) -> None: ...
    def get_alert(self, alert_id: str) -> FraudAlert | None: ...
    def update_alert(self, alert: FraudAlert) -> None: ...
    def list_alerts(
        self,
        *,
        status: AlertStatus | None = None,
        severity: RiskLevel | None = None,
        page: int = 1,
        page_size: int = 20,
    ) -> tuple[list[FraudAlert], int]: ...
    def list_alerts_for_source(
        self,
        *,
        source_type: WorkflowSourceType,
        source_id: str,
    ) -> list[FraudAlert]: ...
    def count_unacknowledged(self) -> int: ...
    def count_by_severity(self) -> dict[str, int]: ...


class DatasetStore(Protocol):
    """Port for dataset and analysis result storage."""

    def save_dataset(self, dataset: Dataset) -> None: ...
    def get_dataset(self, dataset_id: str) -> Dataset | None: ...
    def list_datasets(self) -> list[Dataset]: ...
    def save_transactions(self, dataset_id: str, txns: list[UploadedTransaction]) -> None: ...
    def get_transactions(self, dataset_id: str) -> list[UploadedTransaction]: ...
    def save_result(self, result: AnalysisResult) -> None: ...
    def get_result(self, dataset_id: str) -> AnalysisResult | None: ...
    def list_results(self) -> list[AnalysisResult]: ...
    def total_transactions(self) -> int: ...
    def total_anomalies(self) -> int: ...

