/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List fraud alerts
         * @description Returns a paginated list of fraud alerts with optional status and severity filters.
         */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update alert status
         * @description Transitions an alert status and optionally links it to a case.
         */
        patch: operations["update_alert_status_api_v1_alerts__alert_id__patch"];
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/case": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a case from an alert
         * @description Creates a persistent fraud case from an alert and links the alert to that case in a single workflow step.
         */
        post: operations["create_case_from_alert_api_v1_alerts__alert_id__case_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List audit events
         * @description Returns recent audit events. Admin only.
         */
        get: operations["list_audit_events_api_v1_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current operator profile */
        get: operations["get_current_operator_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate an operator
         * @description Validates operator credentials and returns a JWT access token for subsequent API calls.
         */
        post: operations["login_operator_api_v1_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List fraud cases
         * @description Returns a paginated list of fraud cases with optional status, priority, and analyst filters.
         */
        get: operations["list_cases_api_v1_cases_get"];
        put?: never;
        /**
         * Create a fraud case
         * @description Creates a new fraud case linked to either a reference scenario or an uploaded dataset.
         */
        post: operations["create_case_api_v1_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get case details */
        get: operations["get_case_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a comment to a case
         * @description Appends an analyst note or observation to a fraud case.
         */
        post: operations["add_case_comment_api_v1_cases__case_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update case status
         * @description Transitions a case through its lifecycle: open, investigating, escalated, resolved, or closed.
         */
        patch: operations["update_case_status_api_v1_cases__case_id__status_patch"];
        trace?: never;
    };
    "/api/v1/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dashboard statistics
         * @description Returns aggregate metrics for the analyst dashboard: case counts, alert counts, risk distribution, and recent activity.
         */
        get: operations["get_dashboard_stats_api_v1_dashboard_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List uploaded datasets */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest transactions via API
         * @description Accepts a JSON array of transaction records for programmatic ingestion.
         */
        post: operations["ingest_transactions_api_v1_datasets_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a transaction CSV
         * @description Upload a CSV file with transaction data for fraud analysis. Required columns: transaction_id, account_id, amount, timestamp. Optional: merchant, category, device_fingerprint, ip_country, channel, is_fraud.
         */
        post: operations["upload_dataset_api_v1_datasets_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get analysis results for a dataset */
        get: operations["get_analysis_results_api_v1_datasets__dataset_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run fraud analysis on a dataset
         * @description Executes Benford's Law analysis, statistical outlier detection, velocity spike detection, round-amount structuring detection, and behavioral relationship inference over accounts, devices, merchants, and geographies.
         */
        post: operations["analyze_dataset_api_v1_datasets__dataset_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/case": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a case from a dataset analysis
         * @description Creates a persistent fraud case from a completed dataset analysis using the analysis-generated investigation leads, and links any open dataset alerts to that case.
         */
        post: operations["create_case_from_analysis_api_v1_datasets__dataset_id__case_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain a dataset analysis
         * @description Returns an operator-facing explanation of a completed dataset analysis. Statistical and behavioral scoring remain the source of truth even when the optional Hugging Face explanation provider is active.
         */
        get: operations["get_analysis_explanation_api_v1_datasets__dataset_id__explanation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check platform health
         * @description Returns the overall health status of the platform including database, rate limiter, and seeded data counts.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run fraud investigation
         * @description Executes a full fraud investigation on a reference scenario: text signal extraction, rule-based risk reasoning, graph analysis, and case assembly.
         */
        post: operations["investigate_scenario_api_v1_investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{scenario_id}/case": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a case from a scenario investigation
         * @description Runs the scenario investigation, creates a persistent fraud case from the highest-signal scenario leads, and links any open scenario alerts to that case.
         */
        post: operations["create_case_from_investigation_api_v1_investigations__scenario_id__case_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List fraud scenarios
         * @description Returns all seeded fraud scenarios with baseline risk assessment.
         */
        get: operations["list_scenarios_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get scenario details
         * @description Returns full scenario data including customers, accounts, devices, merchants, and transactions.
         */
        get: operations["get_scenario_api_v1_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the primary workflow guide
         * @description Returns the dataset-first workflow, role stories, scoring guarantees, and copilot positioning used by the frontend workspace.
         */
        get: operations["get_workspace_guide_api_v1_workspace_guide_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountProfile */
        AccountProfile: {
            /** Account Id */
            account_id: string;
            /** Average Monthly Inflow */
            average_monthly_inflow: number;
            /** Chargeback Count */
            chargeback_count: number;
            /** Current Balance */
            current_balance: number;
            /** Customer Id */
            customer_id: string;
            /** Manual Review Count */
            manual_review_count: number;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
        };
        /**
         * ActivityEvent
         * @description A lightweight event for the dashboard activity feed.
         */
        ActivityEvent: {
            /** Actor */
            actor?: string | null;
            /** Description */
            description: string;
            /** Event Type */
            event_type: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Resource Id */
            resource_id?: string | null;
        };
        /** AddCommentBody */
        AddCommentBody: {
            /** Body */
            body: string;
        };
        /** AddCommentResult */
        AddCommentResult: {
            comment: components["schemas"]["CaseComment"];
        };
        /**
         * AlertStatus
         * @enum {string}
         */
        AlertStatus: "new" | "acknowledged" | "investigating" | "resolved" | "false-positive";
        /** AnalysisExplanation */
        AnalysisExplanation: {
            audience: components["schemas"]["ExplanationAudience"];
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Name */
            dataset_name: string;
            /** Deterministic Evidence */
            deterministic_evidence?: string[];
            /** Headline */
            headline: string;
            /** Narrative */
            narrative: string;
            provider_summary: components["schemas"]["ExplanationProviderSummary"];
            /** Recommended Actions */
            recommended_actions?: string[];
            /** Watchouts */
            watchouts?: string[];
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            analysis: components["schemas"]["AnalysisResult"];
        };
        /**
         * AnalysisResult
         * @description Complete analysis output for an uploaded dataset.
         */
        AnalysisResult: {
            /** Analysis Id */
            analysis_id: string;
            /** Anomalies */
            anomalies?: components["schemas"]["AnomalyFlag"][];
            /** Behavioral Insights */
            behavioral_insights?: components["schemas"]["BehavioralInsight"][];
            /** Benford Chi Squared */
            benford_chi_squared: number;
            /** Benford Digits */
            benford_digits?: components["schemas"]["BenfordDigitResult"][];
            /**
             * Benford Is Suspicious
             * @default false
             */
            benford_is_suspicious: boolean;
            /** Benford P Value */
            benford_p_value: number;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Dataset Id */
            dataset_id: string;
            graph_analysis?: components["schemas"]["GraphAnalysisResult"] | null;
            /** Investigation Leads */
            investigation_leads?: components["schemas"]["InvestigationLead"][];
            /**
             * Outlier Count
             * @default 0
             */
            outlier_count: number;
            /**
             * Outlier Pct
             * @default 0
             */
            outlier_pct: number;
            risk_level: components["schemas"]["RiskLevel"];
            /** Risk Score */
            risk_score: number;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Total Anomalies */
            total_anomalies: number;
            /** Total Transactions */
            total_transactions: number;
            /** Velocity Spikes */
            velocity_spikes?: components["schemas"]["VelocitySpike"][];
        };
        /**
         * AnomalyFlag
         * @description A single anomaly detected during analysis.
         */
        AnomalyFlag: {
            /** Affected Entity Id */
            affected_entity_id: string;
            /** Affected Entity Type */
            affected_entity_type: string;
            /** Anomaly Id */
            anomaly_id: string;
            anomaly_type: components["schemas"]["AnomalyType"];
            /** Description */
            description: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Score */
            score: number;
            severity: components["schemas"]["RiskLevel"];
            /** Title */
            title: string;
        };
        /**
         * AnomalyType
         * @enum {string}
         */
        AnomalyType: "benford-violation" | "statistical-outlier" | "velocity-spike" | "graph-cluster" | "round-amount" | "shared-identifier" | "merchant-concentration" | "geographic-drift" | "peer-group-outlier";
        /** AuditEvent */
        AuditEvent: {
            /** Action */
            action: string;
            actor_role?: components["schemas"]["OperatorRole"] | null;
            /** Actor User Id */
            actor_user_id?: string | null;
            /** Actor Username */
            actor_username?: string | null;
            /** Details */
            details?: {
                [key: string]: string;
            };
            /** Event Id */
            event_id: number;
            /** Http Method */
            http_method: string;
            /** Ip Address */
            ip_address?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Path */
            path: string;
            /** Request Id */
            request_id: string;
            /** Resource Id */
            resource_id?: string | null;
            /** Resource Type */
            resource_type: string;
            /** Status Code */
            status_code: number;
            /** User Agent */
            user_agent?: string | null;
        };
        /**
         * BehavioralInsight
         * @description A higher-level inference synthesized from multiple related transactions.
         */
        BehavioralInsight: {
            /** Entities */
            entities?: components["schemas"]["EntityReference"][];
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Insight Id */
            insight_id: string;
            /** Narrative */
            narrative: string;
            severity: components["schemas"]["RiskLevel"];
            /** Title */
            title: string;
        };
        /**
         * BenfordDigitResult
         * @description Benford's Law analysis for a single leading digit.
         */
        BenfordDigitResult: {
            /** Actual Pct */
            actual_pct: number;
            /** Deviation */
            deviation: number;
            /** Digit */
            digit: number;
            /** Expected Pct */
            expected_pct: number;
        };
        /** Body_upload_dataset_api_v1_datasets_upload_post */
        Body_upload_dataset_api_v1_datasets_upload_post: {
            /** File */
            file: string;
        };
        /**
         * CaseComment
         * @description A timestamped note attached to a fraud case by an analyst.
         */
        CaseComment: {
            /** Author Id */
            author_id: string;
            /** Author Name */
            author_name: string;
            /** Body */
            body: string;
            /** Case Id */
            case_id: string;
            /** Comment Id */
            comment_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CaseDatasetDetail */
        CaseDatasetDetail: {
            /** Dataset Id */
            dataset_id: string;
            /** Error Message */
            error_message?: string | null;
            /** Name */
            name: string;
            /** Row Count */
            row_count: number;
            status: components["schemas"]["DatasetStatus"];
            /** Uploaded At */
            uploaded_at: string;
        };
        /**
         * CaseDisposition
         * @enum {string}
         */
        CaseDisposition: "confirmed-fraud" | "false-positive" | "inconclusive" | "referred-to-law-enforcement";
        /**
         * CasePriority
         * @enum {string}
         */
        CasePriority: "low" | "medium" | "high" | "critical";
        /**
         * CaseStatus
         * @enum {string}
         */
        CaseStatus: "open" | "investigating" | "escalated" | "resolved" | "closed";
        /** CreateCaseCommand */
        CreateCaseCommand: {
            /** Assigned Analyst Id */
            assigned_analyst_id?: string | null;
            priority?: components["schemas"]["CasePriority"] | null;
            risk_level?: components["schemas"]["RiskLevel"] | null;
            /** Risk Score */
            risk_score?: number | null;
            /** Scenario Id */
            scenario_id?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** @default scenario */
            source_type: components["schemas"]["WorkflowSourceType"];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** CreateCaseFromAlertResult */
        CreateCaseFromAlertResult: {
            alert: components["schemas"]["FraudAlert"];
            case: components["schemas"]["FraudCase"];
        };
        /** CreateCaseFromAnalysisResult */
        CreateCaseFromAnalysisResult: {
            analysis: components["schemas"]["AnalysisResult"];
            case: components["schemas"]["FraudCase"];
            /** Linked Alerts */
            linked_alerts: components["schemas"]["FraudAlert"][];
        };
        /** CreateCaseFromInvestigationResult */
        CreateCaseFromInvestigationResult: {
            case: components["schemas"]["FraudCase"];
            investigation: components["schemas"]["InvestigationCase"];
            /** Linked Alerts */
            linked_alerts: components["schemas"]["FraudAlert"][];
        };
        /** CreateCaseResult */
        CreateCaseResult: {
            case: components["schemas"]["FraudCase"];
        };
        /** CustomerProfile */
        CustomerProfile: {
            /** Country Code */
            country_code: string;
            /** Customer Id */
            customer_id: string;
            /** Declared Income Band */
            declared_income_band: string;
            /** Full Name */
            full_name: string;
            /** Linked Account Ids */
            linked_account_ids: string[];
            /** Linked Device Ids */
            linked_device_ids: string[];
            /** Segment */
            segment: string;
            /** Watchlist Tags */
            watchlist_tags?: string[];
        };
        /**
         * DashboardStats
         * @description Aggregate metrics for the analyst dashboard overview.
         */
        DashboardStats: {
            /** Alerts By Severity */
            alerts_by_severity?: {
                [key: string]: number;
            };
            /** Avg Risk Score */
            avg_risk_score: number;
            /** Cases By Status */
            cases_by_status?: {
                [key: string]: number;
            };
            /**
             * Completed Analyses
             * @default 0
             */
            completed_analyses: number;
            /** Critical Cases */
            critical_cases: number;
            /**
             * High Risk Analyses
             * @default 0
             */
            high_risk_analyses: number;
            /**
             * Next Recommended Action
             * @default
             */
            next_recommended_action: string;
            /** Open Cases */
            open_cases: number;
            /** Recent Activity */
            recent_activity?: components["schemas"]["ActivityEvent"][];
            /** Risk Distribution */
            risk_distribution?: {
                [key: string]: number;
            };
            /** Total Alerts */
            total_alerts: number;
            /**
             * Total Anomalies Found
             * @default 0
             */
            total_anomalies_found: number;
            /** Total Cases */
            total_cases: number;
            /**
             * Total Datasets
             * @default 0
             */
            total_datasets: number;
            /** Total Scenarios */
            total_scenarios: number;
            /**
             * Total Transactions Analyzed
             * @default 0
             */
            total_transactions_analyzed: number;
            /** Unacknowledged Alerts */
            unacknowledged_alerts: number;
            /** Workflow Stages */
            workflow_stages?: components["schemas"]["WorkflowStageSnapshot"][];
        };
        /** DatasetListResponse */
        DatasetListResponse: {
            /** Datasets */
            datasets: components["schemas"]["DatasetResponse"][];
        };
        /** DatasetResponse */
        DatasetResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Error Message */
            error_message?: string | null;
            /** Name */
            name: string;
            /** Row Count */
            row_count: number;
            status: components["schemas"]["DatasetStatus"];
            /** Uploaded At */
            uploaded_at: string;
        };
        /**
         * DatasetStatus
         * @enum {string}
         */
        DatasetStatus: "uploaded" | "analyzing" | "completed" | "failed";
        /** DeviceProfile */
        DeviceProfile: {
            /** Device Id */
            device_id: string;
            /** Fingerprint */
            fingerprint: string;
            /** Ip Country Code */
            ip_country_code: string;
            /** Linked Customer Ids */
            linked_customer_ids: string[];
            /** Trust Score */
            trust_score: number;
        };
        /** EntityReference */
        EntityReference: {
            /** Display Name */
            display_name: string;
            /** Entity Id */
            entity_id: string;
            entity_type: components["schemas"]["EntityType"];
        };
        /**
         * EntityType
         * @enum {string}
         */
        EntityType: "customer" | "account" | "device" | "merchant" | "transaction" | "note";
        /**
         * ExplanationAudience
         * @enum {string}
         */
        ExplanationAudience: "analyst" | "admin";
        /** ExplanationProviderSummary */
        ExplanationProviderSummary: {
            /** Active Provider */
            active_provider: string;
            /** Notes */
            notes?: string[];
            /** Requested Provider */
            requested_provider: string;
            /** Source Of Truth */
            source_of_truth: string;
        };
        /**
         * FraudAlert
         * @description An auto-generated or manually created alert that may lead to a case.
         */
        FraudAlert: {
            /** Acknowledged At */
            acknowledged_at?: string | null;
            /** Alert Id */
            alert_id: string;
            /** Assigned Analyst Id */
            assigned_analyst_id?: string | null;
            /** Assigned Analyst Name */
            assigned_analyst_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Linked Case Id */
            linked_case_id?: string | null;
            /** Narrative */
            narrative: string;
            /** Resolved At */
            resolved_at?: string | null;
            /** Rule Code */
            rule_code: string;
            /** Scenario Id */
            scenario_id?: string | null;
            severity: components["schemas"]["RiskLevel"];
            /** Source Id */
            source_id: string;
            /** @default scenario */
            source_type: components["schemas"]["WorkflowSourceType"];
            /** @default new */
            status: components["schemas"]["AlertStatus"];
            /** Title */
            title: string;
        };
        /**
         * FraudCase
         * @description A persistent fraud investigation case with lifecycle management.
         */
        FraudCase: {
            /**
             * Alert Count
             * @default 0
             */
            alert_count: number;
            /** Assigned Analyst Id */
            assigned_analyst_id?: string | null;
            /** Assigned Analyst Name */
            assigned_analyst_name?: string | null;
            /** Case Id */
            case_id: string;
            /**
             * Comment Count
             * @default 0
             */
            comment_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            disposition?: components["schemas"]["CaseDisposition"] | null;
            /** @default medium */
            priority: components["schemas"]["CasePriority"];
            /** Resolution Notes */
            resolution_notes?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            risk_level: components["schemas"]["RiskLevel"];
            /** Risk Score */
            risk_score: number;
            /** Scenario Id */
            scenario_id?: string | null;
            /** Sla Deadline */
            sla_deadline?: string | null;
            /** Source Id */
            source_id: string;
            /** @default scenario */
            source_type: components["schemas"]["WorkflowSourceType"];
            /** @default open */
            status: components["schemas"]["CaseStatus"];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FraudScenario */
        FraudScenario: {
            /** Accounts */
            accounts: components["schemas"]["AccountProfile"][];
            /** Customers */
            customers: components["schemas"]["CustomerProfile"][];
            /** Devices */
            devices: components["schemas"]["DeviceProfile"][];
            /** Hypothesis */
            hypothesis: string;
            /** Industry */
            industry: string;
            /** Investigator Notes */
            investigator_notes: components["schemas"]["InvestigatorNote"][];
            /** Merchants */
            merchants: components["schemas"]["MerchantProfile"][];
            /** Scenario Id */
            scenario_id: string;
            /** Summary */
            summary: string;
            /** Tags */
            tags: components["schemas"]["ScenarioTag"][];
            /** Title */
            title: string;
            /** Transactions */
            transactions: components["schemas"]["TransactionRecord"][];
        };
        /** GetAnalysisExplanationResult */
        GetAnalysisExplanationResult: {
            explanation: components["schemas"]["AnalysisExplanation"];
        };
        /** GetCaseResult */
        GetCaseResult: {
            analysis?: components["schemas"]["AnalysisResult"] | null;
            case: components["schemas"]["FraudCase"];
            /** Comments */
            comments?: components["schemas"]["CaseComment"][];
            dataset?: components["schemas"]["CaseDatasetDetail"] | null;
            /** Dataset Transactions */
            dataset_transactions?: components["schemas"]["UploadedTransaction"][];
            investigation?: components["schemas"]["InvestigationCase"] | null;
            /** Investigator Notes */
            investigator_notes?: components["schemas"]["InvestigatorNote"][];
            /** Related Alerts */
            related_alerts?: components["schemas"]["FraudAlert"][];
            /** Scenario Transactions */
            scenario_transactions?: components["schemas"]["TransactionRecord"][];
        };
        /** GetCurrentOperatorResult */
        GetCurrentOperatorResult: {
            principal: components["schemas"]["OperatorPrincipal"];
        };
        /** GetDashboardStatsResult */
        GetDashboardStatsResult: {
            stats: components["schemas"]["DashboardStats"];
        };
        /** GetScenarioResult */
        GetScenarioResult: {
            scenario: components["schemas"]["FraudScenario"];
        };
        /** GetWorkspaceGuideResult */
        GetWorkspaceGuideResult: {
            guide: components["schemas"]["WorkspaceGuide"];
        };
        /**
         * GraphAnalysisResult
         * @description Results from graph-based relationship analysis.
         */
        GraphAnalysisResult: {
            /**
             * Community Count
             * @default 0
             */
            community_count: number;
            /** Connected Components */
            connected_components: number;
            /** Density */
            density: number;
            highest_degree_entity?: components["schemas"]["EntityReference"] | null;
            /**
             * Highest Degree Score
             * @default 0
             */
            highest_degree_score: number;
            /** Hub Entities */
            hub_entities?: components["schemas"]["EntityReference"][];
            /**
             * Risk Amplification Factor
             * @default 1
             */
            risk_amplification_factor: number;
            /** Shortest Path Length */
            shortest_path_length?: number | null;
        };
        /** GraphLink */
        GraphLink: {
            /** Explanation */
            explanation: string;
            /** Relation */
            relation: string;
            source: components["schemas"]["EntityReference"];
            target: components["schemas"]["EntityReference"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** App Name */
            app_name: string;
            /**
             * Database Status
             * @enum {string}
             */
            database_status: "ready" | "unavailable";
            /** Environment */
            environment: string;
            provider_posture: components["schemas"]["ProviderPostureResponse"];
            /**
             * Provider Status
             * @enum {string}
             */
            provider_status: "ready" | "degraded";
            /** Rate Limit Backend */
            rate_limit_backend: string;
            /**
             * Rate Limit Status
             * @enum {string}
             */
            rate_limit_status: "ready" | "degraded" | "unavailable";
            /** Seeded Operators */
            seeded_operators: number;
            /** Seeded Scenarios */
            seeded_scenarios: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** InvestigateScenarioCommand */
        InvestigateScenarioCommand: {
            /** Scenario Id */
            scenario_id: string;
        };
        /** InvestigateScenarioResult */
        InvestigateScenarioResult: {
            investigation: components["schemas"]["InvestigationCase"];
        };
        /** InvestigationCase */
        InvestigationCase: {
            graph_analysis?: components["schemas"]["GraphAnalysisResult"] | null;
            /** Graph Links */
            graph_links: components["schemas"]["GraphLink"][];
            /** Investigation Leads */
            investigation_leads?: components["schemas"]["InvestigationLead"][];
            metrics: components["schemas"]["InvestigationMetrics"];
            provider_summary: components["schemas"]["ProviderSummary"];
            /** Recommended Actions */
            recommended_actions?: string[];
            risk_level: components["schemas"]["RiskLevel"];
            scenario: components["schemas"]["ScenarioOverview"];
            /** Summary */
            summary: string;
            /** Suspicious Transactions */
            suspicious_transactions?: components["schemas"]["TransactionRecord"][];
            /** Text Signals */
            text_signals: components["schemas"]["TextSignal"][];
            /** Top Rule Hits */
            top_rule_hits: components["schemas"]["RuleHit"][];
            /** Total Risk Score */
            total_risk_score: number;
        };
        /**
         * InvestigationLead
         * @description An investigation-ready hypothesis assembled from related findings.
         */
        InvestigationLead: {
            /** Entities */
            entities?: components["schemas"]["EntityReference"][];
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Hypothesis */
            hypothesis: string;
            /** Lead Id */
            lead_id: string;
            /** Lead Type */
            lead_type: string;
            /** Narrative */
            narrative: string;
            /** Recommended Actions */
            recommended_actions?: string[];
            severity: components["schemas"]["RiskLevel"];
            /** Supporting Anomaly Ids */
            supporting_anomaly_ids?: string[];
            /** Title */
            title: string;
        };
        /** InvestigationMetrics */
        InvestigationMetrics: {
            /** Linked Customer Count */
            linked_customer_count: number;
            /** Shared Device Count */
            shared_device_count: number;
            /** Suspicious Transaction Count */
            suspicious_transaction_count: number;
            /** Suspicious Transaction Volume */
            suspicious_transaction_volume: number;
            /** Total Transaction Volume */
            total_transaction_volume: number;
        };
        /** InvestigatorNote */
        InvestigatorNote: {
            /** Author */
            author: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Note Id */
            note_id: string;
            /** Subject Customer Id */
            subject_customer_id: string;
        };
        /** ListAlertsResult */
        ListAlertsResult: {
            /** Alerts */
            alerts: components["schemas"]["FraudAlert"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Count */
            total_count: number;
        };
        /** ListAuditEventsResult */
        ListAuditEventsResult: {
            /** Events */
            events: components["schemas"]["AuditEvent"][];
        };
        /** ListCasesResult */
        ListCasesResult: {
            /** Cases */
            cases: components["schemas"]["FraudCase"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Count */
            total_count: number;
        };
        /** ListScenariosResult */
        ListScenariosResult: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioOverview"][];
        };
        /** LoginCommand */
        LoginCommand: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** LoginResult */
        LoginResult: {
            /** Access Token */
            access_token: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
            principal: components["schemas"]["OperatorPrincipal"];
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** MerchantProfile */
        MerchantProfile: {
            /** Category */
            category: string;
            /** Country Code */
            country_code: string;
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            /** Merchant Id */
            merchant_id: string;
        };
        /** OperatorPrincipal */
        OperatorPrincipal: {
            /** Display Name */
            display_name: string;
            /** Is Active */
            is_active: boolean;
            role: components["schemas"]["OperatorRole"];
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
        };
        /**
         * OperatorRole
         * @enum {string}
         */
        OperatorRole: "analyst" | "admin";
        /** ProviderPostureResponse */
        ProviderPostureResponse: {
            /** Active Explanation Provider */
            active_explanation_provider: string;
            /** Active Reasoning Provider */
            active_reasoning_provider: string;
            /** Active Text Signal Provider */
            active_text_signal_provider: string;
            /** Notes */
            notes: string[];
            /** Requested Explanation Provider */
            requested_explanation_provider: string;
            /** Requested Reasoning Provider */
            requested_reasoning_provider: string;
            /** Requested Text Signal Provider */
            requested_text_signal_provider: string;
        };
        /** ProviderSummary */
        ProviderSummary: {
            /** Active Reasoning Provider */
            active_reasoning_provider: string;
            /** Active Text Provider */
            active_text_provider: string;
            /** Notes */
            notes?: string[];
            /** Requested Reasoning Provider */
            requested_reasoning_provider: string;
            /** Requested Text Provider */
            requested_text_provider: string;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "medium" | "high" | "critical";
        /** RoleStory */
        RoleStory: {
            /** Goal */
            goal: string;
            /** Persona Name */
            persona_name: string;
            platform_role: components["schemas"]["OperatorRole"];
            /** Recommended View */
            recommended_view: string;
            /** Story Id */
            story_id: string;
            /** Success Signal */
            success_signal: string;
            /** Title */
            title: string;
            /** Workflow Steps */
            workflow_steps?: string[];
        };
        /** RuleHit */
        RuleHit: {
            /** Evidence */
            evidence?: components["schemas"]["EntityReference"][];
            /** Narrative */
            narrative: string;
            /** Rule Code */
            rule_code: string;
            /** Title */
            title: string;
            /** Weight */
            weight: number;
        };
        /** ScenarioOverview */
        ScenarioOverview: {
            baseline_risk: components["schemas"]["RiskLevel"];
            /** Hypothesis */
            hypothesis: string;
            /** Industry */
            industry: string;
            /** Scenario Id */
            scenario_id: string;
            /** Summary */
            summary: string;
            /** Tags */
            tags: components["schemas"]["ScenarioTag"][];
            /** Title */
            title: string;
            /** Total Volume */
            total_volume: number;
            /** Transaction Count */
            transaction_count: number;
        };
        /**
         * ScenarioTag
         * @enum {string}
         */
        ScenarioTag: "fraud" | "synthetic-identity" | "account-takeover" | "device-ring" | "cross-border" | "money-mule" | "bust-out" | "first-party";
        /** TextSignal */
        TextSignal: {
            /** Confidence */
            confidence: number;
            /** Label */
            label: string;
            /** Provider */
            provider: string;
            /** Rationale */
            rationale: string;
            /** Signal Id */
            signal_id: string;
            /** Source Id */
            source_id: string;
            source_kind: components["schemas"]["TextSignalKind"];
        };
        /**
         * TextSignalKind
         * @enum {string}
         */
        TextSignalKind: "investigator-note" | "merchant-description";
        /**
         * TransactionChannel
         * @enum {string}
         */
        TransactionChannel: "card-not-present" | "wallet" | "bank-transfer" | "card-present" | "ach";
        /** TransactionIngestBody */
        TransactionIngestBody: {
            /**
             * Name
             * @default api-ingestion
             */
            name: string;
            /** Transactions */
            transactions: {
                [key: string]: unknown;
            }[];
        };
        /** TransactionRecord */
        TransactionRecord: {
            /** Account Id */
            account_id: string;
            /** Amount */
            amount: number;
            channel: components["schemas"]["TransactionChannel"];
            /** Currency */
            currency: string;
            /** Customer Id */
            customer_id: string;
            /** Device Id */
            device_id: string;
            /** Merchant Id */
            merchant_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            status: components["schemas"]["TransactionStatus"];
            /** Transaction Id */
            transaction_id: string;
        };
        /**
         * TransactionStatus
         * @enum {string}
         */
        TransactionStatus: "approved" | "review" | "declined" | "pending";
        /** UpdateAlertStatusBody */
        UpdateAlertStatusBody: {
            /** Linked Case Id */
            linked_case_id?: string | null;
            status: components["schemas"]["AlertStatus"];
        };
        /** UpdateAlertStatusResult */
        UpdateAlertStatusResult: {
            alert: components["schemas"]["FraudAlert"];
        };
        /** UpdateCaseStatusBody */
        UpdateCaseStatusBody: {
            disposition?: components["schemas"]["CaseDisposition"] | null;
            /** Resolution Notes */
            resolution_notes?: string | null;
            status: components["schemas"]["CaseStatus"];
        };
        /** UpdateCaseStatusResult */
        UpdateCaseStatusResult: {
            case: components["schemas"]["FraudCase"];
        };
        /**
         * UploadedTransaction
         * @description A single transaction row from a user-uploaded CSV or API ingestion.
         */
        UploadedTransaction: {
            /** Account Id */
            account_id: string;
            /** Amount */
            amount: number;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Channel
             * @default
             */
            channel: string;
            /**
             * Device Fingerprint
             * @default
             */
            device_fingerprint: string;
            /**
             * Ip Country
             * @default
             */
            ip_country: string;
            /** Is Fraud Label */
            is_fraud_label?: boolean | null;
            /**
             * Merchant
             * @default
             */
            merchant: string;
            /** Row Index */
            row_index: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Transaction Id */
            transaction_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VelocitySpike
         * @description A detected spike in transaction velocity for an entity.
         */
        VelocitySpike: {
            /** Baseline Avg Count */
            baseline_avg_count: number;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Total Amount */
            total_amount: number;
            /** Transaction Count */
            transaction_count: number;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /** Z Score */
            z_score: number;
        };
        /**
         * WorkflowSourceType
         * @enum {string}
         */
        WorkflowSourceType: "scenario" | "dataset";
        /** WorkflowStageSnapshot */
        WorkflowStageSnapshot: {
            /** Description */
            description: string;
            /**
             * Highlighted Count
             * @default 0
             */
            highlighted_count: number;
            /** Highlighted Label */
            highlighted_label: string;
            /** Stage Id */
            stage_id: string;
            /** Title */
            title: string;
            /**
             * Total Count
             * @default 0
             */
            total_count: number;
        };
        /** WorkspaceGuide */
        WorkspaceGuide: {
            /** Llm Positioning Note */
            llm_positioning_note: string;
            /** Primary Workflow Summary */
            primary_workflow_summary: string;
            /** Primary Workflow Title */
            primary_workflow_title: string;
            /** Role Stories */
            role_stories?: components["schemas"]["RoleStory"][];
            /** Scoring Guarantees */
            scoring_guarantees?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["AlertStatus"] | null;
                severity?: components["schemas"]["RiskLevel"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAlertsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_status_api_v1_alerts__alert_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAlertStatusBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateAlertStatusResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_from_alert_api_v1_alerts__alert_id__case_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCaseFromAlertResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_events_api_v1_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAuditEventsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_operator_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCurrentOperatorResult"];
                };
            };
        };
    };
    login_operator_api_v1_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_api_v1_cases_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["CaseStatus"] | null;
                priority?: components["schemas"]["CasePriority"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCasesResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_api_v1_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaseCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCaseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCaseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_case_comment_api_v1_cases__case_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCommentBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddCommentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_status_api_v1_cases__case_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCaseStatusBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateCaseStatusResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_stats_api_v1_dashboard_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDashboardStatsResult"];
                };
            };
        };
    };
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetListResponse"];
                };
            };
        };
    };
    ingest_transactions_api_v1_datasets_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionIngestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_api_v1_datasets_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_v1_datasets_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_results_api_v1_datasets__dataset_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_dataset_api_v1_datasets__dataset_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_from_analysis_api_v1_datasets__dataset_id__case_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCaseFromAnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_explanation_api_v1_datasets__dataset_id__explanation_get: {
        parameters: {
            query?: {
                audience?: components["schemas"]["ExplanationAudience"];
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAnalysisExplanationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    investigate_scenario_api_v1_investigations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigateScenarioCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigateScenarioResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_from_investigation_api_v1_investigations__scenario_id__case_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCaseFromInvestigationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListScenariosResult"];
                };
            };
        };
    };
    get_scenario_api_v1_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetScenarioResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_guide_api_v1_workspace_guide_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetWorkspaceGuideResult"];
                };
            };
        };
    };
}
